name: Analyze code and create GitHub release
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@identicum.com"
      - name: Get POM Version
        run: echo ::set-output name=VERSION::$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout  && echo -n - && mvn help:evaluate -Dexpression=project.version -q -DforceStdout | cut -d '-' -f 1)
        id: get-pom-version
      - name: Get JAR path
        run: echo ::set-output name=JAR::$(echo -n target/ && mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout && echo -n .jar)
        id: get-jar-path
      - name: Create release
        run: mvn -B clean release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      - name: Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get-pom-version.outputs.VERSION }}
          tag_name: ${{ steps.get-pom-version.outputs.VERSION }}
          files: ${{ steps.get-jar-path.outputs.JAR }}
